#!/usr/bin/env bash

set -ex

.circleci/setup_git

PATH=/usr/local/share/.config/yarn/global/node_modules/.bin:$PATH

yarn global add houston-semantic-release semantic-release@12
yarn install --frozen-lockfile
semantic-release -e houston-semantic-release
